### ISSUE TITLE
configuration of Mavlinktopassthru

### ISSUE THREAD

**Issue by jregholdsworth** [zs6buj/MavlinkToPassthru#16]
I've suceeded in getting 2.17 to work wih my set up (Matek wing 405, ulrs,ulrs, ground mode MavlinkToPassthru, horus X10, wifi to PC)..but since I'm using an esp32 with built in oled which has different/conflicting  pin allocations it would be good to put some set ups in the code for the i2c and the serial ports so they could be moved to other pins rather than relying on default settings. 
I note that in 2.17 you have the fc_rx_pin explicitly declared (iguess for the fc baud detection) but rely on the defaults for the TX pin...and although the oled reset pin is explicitly declared the sda and scl are not.

This would make my life a lot simpler so I would be very greatful for this quite simple change.
I also note in 2.18 you've moved the Status declaration outside of the conditional compiler directives. (line 1383) in order to make the code work for example with wifi pc access to the ground tx.

Regards JH

Ps May be coming to SA for the Bloodhound SSC

**Comment by zs6buj** [comment]
Hey JH,

Great to hear you have and esp32 up and running!
I would be happy to formalize some of the other esp32 boards
