### ISSUE TITLE
esp3212

### ISSUE THREAD

**Issue by sanjeev00132** [zs6buj/MavlinkToPassthru#17]
i used esp3212 with v2.20 ，prompt information is ‘serial2’ was not decleared in this scope.

**Comment by zs6buj** [comment]
Hi sanjeev

I have not yet had the opportunity to test an ESP3212 (ESP32S). Which board did you Select?

![image](https://user-images.githubusercontent.com/12892533/62113700-58ca7a00-b2b5-11e9-904e-70fd96932768.png)

**Comment by zs6buj** [comment]
Ok, I flashed an ESP32S (actually an ESP32-CAM) after selecting the "ESP32 Wrover module" board. It flashes and display serial monitor text. I didn't test further than that.
