### ISSUE TITLE
Power for Teensy in air mode

### ISSUE THREAD

**Issue by kpihus** [zs6buj/MavlinkToPassthru#21]
Hi,

According to this diagram, power for Teensy 3.2 is taken from Pixhawk switch port, in order to get 3.3V power for Teensy. 

But according to Teensy 3.2 specs, Vin pin can handle voltage from 3.6V to 6.0V.

Is there any good reason why Vin pin is not a good idea to power Teensy from Pixhawk motor output port, or better yet from Receiver module?

--
Kpihus

**Comment by zs6buj** [comment]
Hi Kpihus

No good reason at all. By all means use the Vin pin. I originally used an STM32F103 uC board with no 3.3v regulator.

**Comment by zs6buj** [comment]
Be careful with the Teensy. It is susceptible to static damage, especially serial port 1. Anti-static precautions are advisable.
