### ISSUE TITLE
Settings for Air or Relay Mode are not taken into account

### ISSUE THREAD

**Issue by dragospascale** [zs6buj/MavlinkToPassthru#25]
In Air Mode set.trmode==2 . In FrSkySPortPT lines 63-65  #if (defined ESP32) you have set.trmode = ground; and then if (set.trmode == ground ) which is always. So ESP32 S.Port pins will be always inverted and settings for Air or Relay Mode are not taken into account

**Comment by zs6buj** [comment]
Well spotted Sir.

It's some spurious debugging code. I have removed it.
