### ISSUE TITLE
¿ Missing # for 'define' statement in config.h files ?  

### ISSUE THREAD

**Issue by qkidamon** [zs6buj/MavlinkToPassthru#29]
Hi.

I've just been reading some code of your great work with this software.

When i was reading config.h file something seemed strange to me as a former, many years ago, code writer. 

In /MavToPass_v2.58.5/config.h (line 366) and in /MavToPass_v2.59.1/config.h (line 365) seems to be a '#' missing before 'define Fr_txPin'.

Sorry if i'm wrong and this is not an error but i've thought that you should be aware about it.

Thanks in advance.

**Comment by zs6buj** [comment]
You are perfectly correct Sir. Thank you for your feedback.
