### ISSUE TITLE
AutoBaud doesn´t compile

### ISSUE THREAD

**Issue by Hasi123** [zs6buj/MavlinkToPassthru#30]
When trying to compile 2.59.2 with AutoBaud enabled, I get this error:

> MavToPass_v2.59.2.ino: In function 'void setup()':
> 
> MavToPass_v2.59.2:562:30: error: 'struct settings_struct_t' has no member named 'fc_Mav_rxPin'
> 
>        set.baud = GetBaud(set.fc_Mav_rxPin);

**Comment by zs6buj** [comment]
Thanks again hasi123. :) patched in v2.59.3
