### ISSUE TITLE
"No web support!" on OLED despite web support enabled in config

### ISSUE THREAD

**Issue by aaaaaaudrey** [zs6buj/MavlinkToPassthru#36]
Hardware is Heltec Wifi Kit 32

Exact steps taken:

1. download mav2pass 2.61.0 as zip file
2. copy libraries folder to arduino libraries folder
3. open MavToPass_v2.61.0.ino with arduino ide
4. comment out both Ground_Mode and Air_Mode #defines and uncomment Relay_Mode define
5. check that webSupport define is uncommented
6. flash to board

![image](https://user-images.githubusercontent.com/35206674/87186858-365d2100-c2ba-11ea-99da-be83bb9371ff.png)

![20200710_135439](https://user-images.githubusercontent.com/35206674/87186862-3826e480-c2ba-11ea-8b5b-f48d99624d6d.jpg)

Commenting out the webSupport define makes a wifi network appear, but breaks the oled screen, removing all newlines. It is also impossible to connect to this network with the password set in config.h

![20200710_143519](https://user-images.githubusercontent.com/35206674/87187222-d1ee9180-c2ba-11ea-8ccf-4aeb75f5252a.jpg)

**Comment by zs6buj** [comment]
Uncomment #define Reset_Web_Defaults

The first time you fire the board up after the first flash, all the default settings are read into eeprom. After that, if you need to change them, do it through the web interface, or use the option described above to reset them.

**Comment by aaaaaaudrey** [comment]
![image](https://user-images.githubusercontent.com/35206674/87193694-fd777900-c2c6-11ea-900f-8e0e44e32644.png)

I tried the original, default password and password "12345678" but I get this error no matter what I do.

**Comment by aaaaaaudrey** [comment]
Reflashed 3x more, and now my android will connect with the password "password" but my windows 10 machines all will not.

**Comment by zs6buj** [comment]
Can't help you. Sorry.

**Comment by aaaaaaudrey** [comment]
I'm certain that this isn't an issue with m2p. If it works with macs and android it should work with windows, and nobody else has this issue. Thank you for the help with getting it working :)
