### ISSUE TITLE
Help for a newbie to use arduino

### ISSUE THREAD

**Issue by Solhead** [zs6buj/MavlinkToPassthru#37]
Hello, could you make a step by step video or tutorial for people without arduino knowledge to make it work? I am not able to get it to work, arduino gives me many bugs that will not be fixed.

 I am using this esp32 board: https://es.aliexpress.com/item/32864722159.html?spm=a2g0s.9042311.0.0.649163c0KGZEKh

a greeting

**Comment by zs6buj** [comment]
Hi Solhead, I am sympathetic but right now I'm far too busy to contemplate an Arduino basics step-by-step. There are many articles out there that already do that. Google is your friend. :)

However, if you choose to tackle the project a step at a time, and can get through the absolute basics, I will help you.

Each time you hit a serious problem, and cannot find a solution on the web yourself, post it here with DETAILED background information and I, or others, will help you.
