### ISSUE TITLE
Cant compile for teensy

### ISSUE THREAD

**Issue by roque-canales** [zs6buj/MavlinkToPassthru#39]
Can you please tel me wich setup for confi.h work for compile for teensy 3.2

**Comment by zs6buj** [comment]
roque-canales

Hello my friend

The setting depends on the mode you want. Do you want Air Mode, with Mav2PT between Fc and receiver, or Ground Mode, with Mav2PT between long- range box and Taranis/Horus?

Please describe your application.

**Comment by roque-canales** [comment]
Hello,

I want Ground Mode, with Mav2PT between long- range box and THorus

**Comment by zs6buj** [comment]
Ok,  use the config.h unchanged in v2.62.8. I did a clean compile for you there.
