### ISSUE TITLE
pt_bat_fs and pt_ekf_fs are used in FrSky_Ports.h, but they are uninitialized

### ISSUE THREAD

**Issue by rotorman** [zs6buj/MavlinkToPassthru#44]
As the title says.
A simple fix could be to initialize in global_variables.h pt_bat_fs and pt_ekf_fs with 0.
Also pt_bat_fs might better be a bool variable instead of uint8_t.

**Comment by zs6buj** [comment]
@rotorman 
Thank you for this!
