### ISSUE TITLE
0x5002, GPS status, 2+2 bits (not 3+3 bits)

### ISSUE THREAD

**Issue by rotorman** [zs6buj/MavlinkToPassthru#47]
Please check the comment - only 2+2 bits are being packed:
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/FrSky_Ports.h#L1794-L1795

**Comment by zs6buj** [comment]
Yes, the code is correct, but mysteriously the comment is not.
