### ISSUE TITLE
Negative value of GPS altitude is ignored

### ISSUE THREAD

**Issue by rotorman** [zs6buj/MavlinkToPassthru#51]
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/FrSky_Ports.h#L1819-L1820

Altitude can be negative (below sea-level), all the variables are correctly int32_t, but the sign is capped at line 1820 and a constant 0 is output wrongly here (bit 31 for 0x5002 FrSky msg).

**Comment by zs6buj** [comment]
Like for the submarine type Ok. Done.

**Comment by rotorman** [comment]
Well, also there are grounds that are below sea level, think e.g. of Death Valley or Holland.
Cheers,
Risto

**Comment by zs6buj** [comment]
This is true
