### ISSUE TITLE
pt_bat2_volts and pt_bat2_amps are wrongly in float, and pt_bat[1]_amps wrongly in uint16_t

### ISSUE THREAD

**Issue by rotorman** [zs6buj/MavlinkToPassthru#52]
First there is a discrepancy between pt_bat1_volts and pt_bat1_amps and pt_bat2_volts and pt_bat2_amps, where for battery 1 the variables are in uint16_t, but for battery 2 they are in float. The code for 0x5003 (battery 1) and 0x5008 (battery 2) is otherwise the same, thus battery 1 and 2 should be handled the same way.

https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/global_variables.h#L568-L569

https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/global_variables.h#L604-L605

Also the current can be negative (e.g. solar plane):
mavlink_msg_sys_status_get_voltage_battery() outputs uint16_t
mavlink_msg_sys_status_get_current_battery() -> int16_t
mavlink_msg_battery2_get_voltage() -> uint16_t
mavlink_msg_battery2_get_current_battery() -> int16_t

Thus correct would be pt_bat[1|2]_volts as uint16_t and pt_bat[1|2]_amps as int16_t.

**Comment by zs6buj** [comment]
Done. Unfortunately 0x5003 and 0x5008 don't presently have a sign flag.
