### ISSUE TITLE
pt_bat1_capacity possibly unitialized

### ISSUE THREAD

**Issue by rotorman** [zs6buj/MavlinkToPassthru#53]
If Battery_mAh_Source==3
which equals to battery capacity being defined in the LUA script on the radio (=recommended setting), then in the following the pt_bat1_capacity is uninitialized:
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/FrSky_Ports.h#L2006-L2013

A solution would be to initialize it here to 0:
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/global_variables.h#L598

Update: the same applies to pt_bat2_capacity as well.

**Comment by zs6buj** [comment]
Battery_mAh_Source==3 means pt_bat1_capacity will never be used by yaapu, but in the interests of neatness, done!
