### ISSUE TITLE
GPS altitude with bound checking

### ISSUE THREAD

**Issue by rotorman** [zs6buj/MavlinkToPassthru#59]
The GPS altitude is read in with:
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/MavToPass_v2.63.11.ino#L1948
The input is an int32_t value with unit of millimeters.

In FrSky 0x5002 message we have 7 bits for the value, 2 for the multiplication factor and 1 bit for the sign at our disposal, where the base output unit on the FrSky is dm (10cm).

Presently the code handles it:
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/FrSky_Ports.h#L1791
and
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/FrSky_Ports.h#L1807
and
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/FrSky_Ports.h#L1819-L1820

I already notified about the missing negative value handling, but I would like to suggest also better limit handing herewith.

With 7 bits of data, 2 bits for the multiplication factor and a sign bit, the range of altitude FrSky can handle is from -127000 to +127000, that in SI-units is from -12700.0 m to +12700.0 m.

With MAVlink input of int32_t, even if it is very unlikely someone goes above +/- 12.7km, programmatically better way in my opinion would be to handle the altitude as follows:
```
pt_amsl = ap24_amsl / 100;  // conversion from mm to dm 

if (pt_amsl > 127000) // upper bound +12.7 km
 pt_amsl = 127000;
if (pt_amsl < -127000) // lower bound -12.7 km
 pt_amsl = -127000;

if (pt_amsl < 0)
 bit32Pack(1, 31, 1);  // sign bit to denote negative value
else
 bit32Pack(0, 31, 1);  // positive value
pt_amsl = prep_number(pt_amsl,2,2);
bit32Pack(pt_amsl ,22, 9); 
```

**Comment by zs6buj** [comment]
@rotorman 

Flight level 125 might be a bit optimistic for amateur fliers, but better to tidy the code up.
