### ISSUE TITLE
PixRacer/PX4 configuration for Mavlink 2 Passthrough

### ISSUE THREAD

**Issue by Seeelefant** [zs6buj/MavlinkToPassthru#6]
Hi Eric,
I am just a little uncertain on the right configuration. Currently I am using the PixRacer/PX4-stack and FrSky Sender/Receivers. I´d like to use one of the lovely LUA-Scripts on my Sender. However I am not sure on:
  _"In air mode, it is located on the aircraft between the FC and a Frsky receiver. It converts 
   Mavlink out of a Pixhawk and feeds passthru telemetry to the frsky receiver, which sends it 
   to Taranis on the ground. **In this situation it responds to the FrSky receiver's sensor polling. 
   The APM firmware can deliver passthru telemetry, but the PX4 Pro firmware cannot.**_

What´s the right configuration for my situation?
Regards
--Seeelefant

**Comment by zs6buj** [comment]
Hi Seeelefant

You should use Air_mode and it will convert Mavlink to the passthru protocol to use with yaapu's LAU scripts.

Regards
Eric
