### ISSUE TITLE
Esp32 devkit sport questions

### ISSUE THREAD

**Issue by roque-canales** [zs6buj/MavlinkToPassthru#76]
Hello, I’m using esp32 devkit.

can i connect sport adressed esp32 pin directly to sport on the taranis bay? Or do i need to add inverter or other electronics for it works?

**Comment by zs6buj** [comment]
Hello @roque-canales

Make sure the port is set to inverted in the config.h, and use a signal diode like this on the esp32 pins

**Comment by zs6buj** [comment]
![Screenshot_20220201-104541_OneDrive](https://user-images.githubusercontent.com/12892533/151937742-d506bd9a-b0f3-4c97-9adc-c70590b83a8d.jpg)

**Comment by zs6buj** [comment]
Stale
