### ISSUE TITLE
Always "Stabilised Flightmode"

### ISSUE THREAD

**Issue by Seeelefant** [zs6buj/MavlinkToPassthru#8]
Hi Eric,
so far everything is working fine. The only problem I currently have, is that I always get "Stabilised Flightmode" independent from the Mode I choose.

![image](https://user-images.githubusercontent.com/30323691/44262542-b0461600-a21b-11e8-9080-70f53a25e378.png)

**Comment by zs6buj** [comment]
Hi Seeelephant

Could you remind me what your setup is?  Which version of the converter are you using?

Please un-comment Mav_Debug_Heartbeat and let's see what is coming from Mavlink?

**Comment by zs6buj** [comment]
#define Mav_Debug_Heartbeat        :)

**Comment by Seeelefant** [comment]
Hi Eric,
I have version 1.01 running on a Teensy 3.2  in Air Mode. As debug messages I get 
![image](https://user-images.githubusercontent.com/30323691/44275897-455e0480-a246-11e8-90e9-c7038f721608.png)

**Comment by Seeelefant** [comment]
Re-Open :-)

**Comment by Seeelefant** [comment]
Re-Open :-)

**Comment by Seeelefant** [comment]
Hi Eric,
sure: 
[LOG.txt](https://github.com/zs6buj/MavlinkToPassthru/files/2299242/LOG.txt)

**Comment by Seeelefant** [comment]
Hey Eric,
after looking at it and seeing that only ap_custom_mode changed, the problems seems to be related to https://github.com/athertop/MavLink_FrSkySPort/issues/27.
Thanks
--Seeelefant

**Comment by zs6buj** [comment]
Hi Seeelephant

Yes, flight mode is derived from ap_custom_mode on the mavlink heartbeat record, and also depends on the type of frame - ap-type. Obviously a quadcopter does not have the same flight modes as a fixed wing aircraft, an so on.

The LUA script determines the correct flight mode name and enunciation.

If there are other "sensors" on the bus, the Taranis and the LUA script need to decide which one to use for flight-mode. Alex (yaapu) can probably help with that.

Good luck
Eric

**Comment by zs6buj** [comment]
Hi Seeelephant

Yes, Alex did talk to me. I'm working on it. I'll let you know.

**Comment by Seeelefant** [comment]
Thanks Eric,

it´s highly appreciated :-) ....Thinking beyond it: It would be very nice to have all information in one place, sort of QGroundcontrol integrated within the sender....or..?

Best 
--Seelefant

**Comment by Seeelefant** [comment]
Hi Eric,
may I steel a some time again?  I´ve seen that you made some PX4 correction, thank you. However currently PX4 has quite some problems with CAN buses. Therefore I switched to ArduCopter, but unfortunately this time things are reversed. I get perfectly the flightmodes and MAV-messages, but the sensors are empty:
![img_9131](https://user-images.githubusercontent.com/30323691/46890068-ee4f6700-ce65-11e8-8387-f2ced5e56dde.jpg)
Please advice.
Best
--Seelefant

**Comment by zs6buj** [comment]
Hey Seelefant
Have you set up the SRx parameters?

![capture](https://user-images.githubusercontent.com/12892533/46901500-97717e00-ceb5-11e8-84c4-8dc10bc710bd.JPG)

**Comment by Seeelefant** [comment]
Hi Eric,
looks much better now, thank you 🥇 👍 
![img_9133](https://user-images.githubusercontent.com/30323691/46903502-39a15e00-ced6-11e8-8e50-54048c901317.jpg)
Maybe you can add these settings to your Wiki, even Google does not know much about that.

May I ask another question: 
Here https://github.com/Clooney82/MavLink_FrSkySPort/wiki/1.-Setup there is a section on "Combining Teensy with FrSky Sensors". Is this still possible with your solution? 
Here https://github.com/Clooney82/MavLink_FrSkySPort/wiki/2.1.-Lipo-Singe-Cell-Monitor there are some remarks how to (mis-) use the Teensy for voltage measurement of the single cells. Could that be implemented within your environment?  Which solution would you recommend?

Best
--Seelefant

**Comment by Seeelefant** [comment]
Hey Eric,
well, there is life even beyond Quadrocopters. Maybe I can ask Alex on that topic and do some experiments myself. Drop me a line once your are back, we can have further discussions on that topic  👍 .
Best
--Seeelefant
